# Generated by Django 3.2 on 2021-04-21 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('iNat_user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('team', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_id', models.IntegerField(default=0)),
                ('taxa', models.CharField(default='Undefined', max_length=20)),
                ('hp', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('evasion', models.IntegerField(default=0)),
                ('accuracy', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('total_xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('num_of_confirmations', models.IntegerField(default=0)),
                ('move1', models.CharField(default='Tackle', max_length=50)),
                ('move2', models.CharField(blank=True, max_length=50)),
                ('move3', models.CharField(blank=True, max_length=50)),
                ('move4', models.CharField(blank=True, max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.player')),
            ],
        ),
    ]
