# Generated by Django 3.2 on 2021-04-21 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='move1',
            new_name='move_1',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='move2',
            new_name='move_2',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='move3',
            new_name='move_3',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='move4',
            new_name='move_4',
        ),
    ]
