# Generated by Django 3.2 on 2021-04-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210421_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.JSONField(default=list, null=True),
        ),
    ]
