# Generated by Django 3.2 on 2021-04-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='name',
            field=models.CharField(default='Observation', max_length=50),
        ),
    ]
