# Generated by Django 3.2 on 2021-04-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_observation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='image_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='observation',
            name='quality',
            field=models.CharField(default='casual', max_length=20),
        ),
        migrations.AddField(
            model_name='observation',
            name='wiki_link',
            field=models.CharField(default='https://en.wikipedia.org/wiki/Main_Page', max_length=100),
        ),
    ]
