# Generated by Django 3.2 on 2021-04-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210429_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='num_of_obs',
            field=models.IntegerField(default=0),
        ),
    ]
