# Generated by Django 3.2 on 2021-05-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210504_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AddField(
            model_name='observation',
            name='is_on_team',
            field=models.BooleanField(default=False),
        ),
    ]
